// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_remote_logger/test/remote_logger_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:flutter_remote_logger/src/core/device_info.dart' as _i10;
import 'package:flutter_remote_logger/src/core/session_manager.dart' as _i8;
import 'package:flutter_remote_logger/src/models/log_entry.dart' as _i4;
import 'package:flutter_remote_logger/src/models/session_info.dart' as _i7;
import 'package:flutter_remote_logger/src/storage/log_storage.dart' as _i2;
import 'package:flutter_remote_logger/src/uploader/log_uploader.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LogStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogStorage extends _i1.Mock implements _i2.LogStorage {
  MockLogStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [sessionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> write(_i4.LogEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#write, [entry]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.File?> getSessionFile() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionFile, []),
            returnValue: _i3.Future<_i5.File?>.value(),
          )
          as _i3.Future<_i5.File?>);
}

/// A class which mocks [LogUploader].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogUploader extends _i1.Mock implements _i6.LogUploader {
  MockLogUploader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> uploadSession(
    _i5.File? logFile,
    _i7.SessionInfo? sessionInfo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadSession, [logFile, sessionInfo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> identifyUser(String? deviceId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#identifyUser, [deviceId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionManager extends _i1.Mock implements _i8.SessionManager {
  MockSessionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get sessionId =>
      (super.noSuchMethod(
            Invocation.getter(#sessionId),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#sessionId),
            ),
          )
          as String);

  @override
  int get startTime =>
      (super.noSuchMethod(Invocation.getter(#startTime), returnValue: 0)
          as int);
}

/// A class which mocks [DeviceInfoProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoProvider extends _i1.Mock
    implements _i10.DeviceInfoProvider {
  MockDeviceInfoProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> getDeviceMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceMetadata, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<String> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i3.Future<String>.value(
              _i9.dummyValue<String>(this, Invocation.method(#getDeviceId, [])),
            ),
          )
          as _i3.Future<String>);
}
